---
version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./conf:/conf
      - ./work:/work
    ports:
        - 53:53
    restart: unless-stopped

networks:
  default:
    name: $NETWORK
    external: true
